### ISSUE TITLE
"else path not taken" for class in ES6

### ISSUE THREAD

**Issue by brunoosilva** [cb1kenobi/gulp-babel-istanbul#12]
I hava a problem with the coverage, look: 

![image](https://cloud.githubusercontent.com/assets/3465257/20882412/fa2e2902-bac7-11e6-8285-fafe909234c6.png)

But, written in this way, it works:
![image](https://cloud.githubusercontent.com/assets/3465257/20882463/352be10c-bac8-11e6-8577-6d38316d4aef.png)
![image](https://cloud.githubusercontent.com/assets/3465257/20882470/3e1b0cd4-bac8-11e6-8937-135ed1df9ed6.png)

* Maybe, this way is not correct. Maybe, no best practice.

**Comment by cb1kenobi** [comment]
Yeah, I've seen similar things with other syntax such as inline ifs: `foo ? 'bar' : 'baz'`. I don't know if what you're seeing is a visual thing or is it affecting the totals too. I'm guessing it doesn't affect the totals and it's just a bug in the report generation.

`gulp-babel-istanbul` uses the latest `babel-istanbul` v0.11.0. `babel-istanbul` is (I believe) developed by the Yahoo! team as a drop-in replacement for Istanbul. However `babel-istanbul` != `istanbul`. I'm not sure that this would be an issue with `istanbul` directly. `babel-istanbul` has been touched in 5 months and I have no idea if it's still maintained.

So, with that said, this isn't a bug with `gulp-babel-istanbul`.

Perhaps `gulp-babel-istanbul` should switch to `istanbul`? I'm not sure how much work that is. I can investigate that, but not for several weeks. I'm swamped with work. :)

**Comment by brunoosilva** [comment]
Thank you for your answer.

Maybe yes, but I'll make a fork to see if I can help.

Imagine that it is not your plugin's problem but rather the calculation.

Also open a new issue for istanbul: https://github.com/gotwarlost/istanbul/issues/735
