### ISSUE TITLE
babelIstanbul not defined in documentation

### ISSUE THREAD

**Issue by JustinLivi** [cb1kenobi/gulp-babel-istanbul#9]
The README references `babelIstanbul` but this variable is not defined anywhere in the scope of the example. Is this supposed to be `istanbul` (the instance of gulp-babel-istanbul?)

**Comment by cb1kenobi** [comment]
@JustinLivi You are correct! Thank you for bringing this to my attention. I fixed it.

I also took this opportunity to update the NPM dependencies. gulp-babel-istanbul@1.4.0 is published and ready to rock.
